### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by nmaster2042** [pothosware/SoapyFCDPP#1]
I'm using utuntu 18.04

$ meson build

`The Meson build system
Version: 0.45.1
Source dir: /home/nicolas/Applis/SDR/SoapyFCDPP/SoapyFCDPP
Build dir: /home/nicolas/Applis/SDR/SoapyFCDPP/SoapyFCDPP/build
Build type: native build
Project name: SoapyFCDPP
Native C compiler: cc (gcc 7.3.0 "cc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0")
Native C++ compiler: c++ (gcc 7.3.0 "c++ (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency SoapySDR found: YES 0.7.0
Native dependency hidapi-libusb found: YES 0.8.0-rc1
Native dependency alsa found: YES 1.1.3
Build targets in project: 1
Found ninja-1.8.2 at /usr/bin/ninja`

But Build fails:

$ ninja -C build

`ninja: Entering directory `build'
[3/4] Compiling C++ object 'soapyfcdpp@sha/SoapyFCDPP.cpp.o'.
FAILED: soapyfcdpp@sha/SoapyFCDPP.cpp.o 
c++  -Isoapyfcdpp@sha -I. -I.. -I/usr/local/include -I/usr/include/alsa -I/usr/include/hidapi -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++11 -O0 -g -fPIC -MD -MQ 'soapyfcdpp@sha/SoapyFCDPP.cpp.o' -MF 'soapyfcdpp@sha/SoapyFCDPP.cpp.o.d' -o 'soapyfcdpp@sha/SoapyFCDPP.cpp.o' -c ../SoapyFCDPP.cpp
In file included from ../SoapyFCDPP.cpp:1:0:
../SoapyFCDPP.hpp: In constructor ‘SoapyFCDPP::SoapyFCDPP(const string&)’:
../SoapyFCDPP.hpp:39:12: warning: ‘SoapyFCDPP::d_frequency’ will be initialized after [-Wreorder]
     double d_frequency;
            ^~~~~~~~~~~
../SoapyFCDPP.hpp:38:18: warning:   ‘const double SoapyFCDPP::d_sample_rate’ [-Wreorder]
     const double d_sample_rate;
                  ^~~~~~~~~~~~~
../SoapyFCDPP.cpp:7:1: warning:   when initialized here [-Wreorder]
 SoapyFCDPP::SoapyFCDPP(const std::string &path) :
 ^~~~~~~~~~
../SoapyFCDPP.cpp: In member function ‘virtual int SoapyFCDPP::readStream(SoapySDR::Stream*, void* const*, size_t, int&, long long int&, long int)’:
../SoapyFCDPP.cpp:167:86: error: no matching function for call to ‘min(uint32_t&, const size_t&)’
     frames = snd_pcm_readi(d_pcm_handle, &d_buff[0], std::min(d_period_size, numElems));
                                                                                      ^
In file included from /usr/include/c++/7/vector:60:0,
                 from /usr/local/include/SoapySDR/Types.hpp:14,
                 from /usr/local/include/SoapySDR/Device.hpp:14,
                 from ../SoapyFCDPP.hpp:12,
                 from ../SoapyFCDPP.cpp:1:
/usr/include/c++/7/bits/stl_algobase.h:195:5: note: candidate: template<class _Tp> const _Tp& std::min(const _Tp&, const _Tp&)
     min(const _Tp& __a, const _Tp& __b)
     ^~~
/usr/include/c++/7/bits/stl_algobase.h:195:5: note:   template argument deduction/substitution failed:
../SoapyFCDPP.cpp:167:86: note:   deduced conflicting types for parameter ‘const _Tp’ (‘unsigned int’ and ‘size_t {aka long unsigned int}’)
     frames = snd_pcm_readi(d_pcm_handle, &d_buff[0], std::min(d_period_size, numElems));
                                                                                      ^
In file included from /usr/include/c++/7/vector:60:0,
                 from /usr/local/include/SoapySDR/Types.hpp:14,
                 from /usr/local/include/SoapySDR/Device.hpp:14,
                 from ../SoapyFCDPP.hpp:12,
                 from ../SoapyFCDPP.cpp:1:
/usr/include/c++/7/bits/stl_algobase.h:243:5: note: candidate: template<class _Tp, class _Compare> const _Tp& std::min(const _Tp&, const _Tp&, _Compare)
     min(const _Tp& __a, const _Tp& __b, _Compare __comp)
     ^~~
/usr/include/c++/7/bits/stl_algobase.h:243:5: note:   template argument deduction/substitution failed:
../SoapyFCDPP.cpp:167:86: note:   deduced conflicting types for parameter ‘const _Tp’ (‘unsigned int’ and ‘size_t {aka long unsigned int}’)
     frames = snd_pcm_readi(d_pcm_handle, &d_buff[0], std::min(d_period_size, numElems));
                                                                                      ^
In file included from /usr/include/c++/7/algorithm:62:0,
                 from ../SoapyFCDPP.cpp:4:
/usr/include/c++/7/bits/stl_algo.h:3450:5: note: candidate: template<class _Tp> _Tp std::min(std::initializer_list<_Tp>)
     min(initializer_list<_Tp> __l)
     ^~~
/usr/include/c++/7/bits/stl_algo.h:3450:5: note:   template argument deduction/substitution failed:
../SoapyFCDPP.cpp:167:86: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘unsigned int’
     frames = snd_pcm_readi(d_pcm_handle, &d_buff[0], std::min(d_period_size, numElems));
                                                                                      ^
In file included from /usr/include/c++/7/algorithm:62:0,
                 from ../SoapyFCDPP.cpp:4:
/usr/include/c++/7/bits/stl_algo.h:3456:5: note: candidate: template<class _Tp, class _Compare> _Tp std::min(std::initializer_list<_Tp>, _Compare)
     min(initializer_list<_Tp> __l, _Compare __comp)
     ^~~
/usr/include/c++/7/bits/stl_algo.h:3456:5: note:   template argument deduction/substitution failed:
../SoapyFCDPP.cpp:167:86: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘unsigned int’
     frames = snd_pcm_readi(d_pcm_handle, &d_buff[0], std::min(d_period_size, numElems));
                                                                                      ^
../SoapyFCDPP.cpp: In member function ‘virtual void SoapyFCDPP::setGain(int, size_t, const string&, double)’:
../SoapyFCDPP.cpp:261:21: warning: suggest parentheses around comparison in operand of ‘!=’ [-Wparentheses]
     } else if (name == "IF" != d_if_gain != value){
                ~~~~~^~~~~~~
../SoapyFCDPP.cpp:261:29: warning: suggest parentheses around comparison in operand of ‘!=’ [-Wparentheses]
     } else if (name == "IF" != d_if_gain != value){
                ~~~~~~~~~~~~~^~~~~~~~~~~~
ninja: build stopped: subcommand failed.`

**Comment by guruofquality** [comment]
Looks like some type mismatch for std::min, I added a cmake build and fixed some of the warnings/errors. I dont have a FCDPP, so thats the best I can do for now. Please send pull requests if you find something implementation-wise to fix. Hope this helps!

**Comment by ast** [comment]
@guruofquality thanks for fixing my bugs while I sleep 👍
@nmaster2042 hope you get it working!

**Comment by nmaster2042** [comment]
@guruofquality: thanks, it builds now with cmake
