### ISSUE TITLE
Compile failed with SoapySDR 0.8.0

### ISSUE THREAD

**Issue by ea3grn** [pothosware/SoapyFCDPP#10]
Meson compile failed with this error:
3/5] Compiling C++ object 'soapyfcdpp@sha/SoapyFCDPP.cpp.o'.
FAILED: soapyfcdpp@sha/SoapyFCDPP.cpp.o 
c++ -Isoapyfcdpp@sha -I. -I.. -I/usr/local/include -I/usr/include/alsa -I/usr/include/hidapi -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++11 -g -fPIC -ggdb -mcpu=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -funsafe-math-optimizations -MD -MQ 'soapyfcdpp@sha/SoapyFCDPP.cpp.o' -MF 'soapyfcdpp@sha/SoapyFCDPP.cpp.o.d' -o 'soapyfcdpp@sha/SoapyFCDPP.cpp.o' -c ../SoapyFCDPP.cpp
../SoapyFCDPP.cpp:159:6: error: no declaration matches ‘void SoapyFCDPP::convertCS16toCF32(void*, void*, size_t)’
 void SoapyFCDPP::convertCS16toCF32(void *dst, void *src, size_t samples)
      ^~~~~~~~~~
../SoapyFCDPP.cpp:159:6: note: no functions named ‘void SoapyFCDPP::convertCS16toCF32(void*, void*, size_t)’
In file included from ../SoapyFCDPP.cpp:5:
../SoapyFCDPP.hpp:29:7: note: ‘class SoapyFCDPP’ defined here
 class SoapyFCDPP : public SoapySDR::Device
       ^~~~~~~~~~
ninja: build stopped: subcommand failed.

Also tried with cmake, with error:

[ 20%] Building CXX object CMakeFiles/FCDPPSupport.dir/SoapyFCDPP/SoapyFCDPP.cpp.o
/usr/src/SoapyFCDPP/SoapyFCDPP/SoapyFCDPP.cpp:159:6: error: no declaration matches ‘void SoapyFCDPP::convertCS16toCF32(void*, void*, size_t)’
 void SoapyFCDPP::convertCS16toCF32(void *dst, void *src, size_t samples)
      ^~~~~~~~~~
/usr/src/SoapyFCDPP/SoapyFCDPP/SoapyFCDPP.cpp:159:6: note: no functions named ‘void SoapyFCDPP::convertCS16toCF32(void*, void*, size_t)’
In file included from /usr/src/SoapyFCDPP/SoapyFCDPP/SoapyFCDPP.cpp:5:
/usr/src/SoapyFCDPP/SoapyFCDPP/SoapyFCDPP.hpp:29:7: note: ‘class SoapyFCDPP’ defined here
 class SoapyFCDPP : public SoapySDR::Device
       ^~~~~~~~~~
/usr/src/SoapyFCDPP/SoapyFCDPP/SoapyFCDPP.cpp: In member function ‘virtual int SoapyFCDPP::readStream(SoapySDR::Stream*, void* const*, size_t, int&, long long int&, long int)’:
/usr/src/SoapyFCDPP/SoapyFCDPP/SoapyFCDPP.cpp:216:13: warning: this statement may fall through [-Wimplicit-fallthrough=]
             if(n_err >= 0) {
             ^~
/usr/src/SoapyFCDPP/SoapyFCDPP/SoapyFCDPP.cpp:228:9: note: here
         case SND_PCM_STATE_XRUN:
         ^~~~
make[2]: *** [CMakeFiles/FCDPPSupport.dir/build.make:63: CMakeFiles/FCDPPSupport.dir/SoapyFCDPP/SoapyFCDPP.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/FCDPPSupport.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

Using SoapySDR version 0.8.0:

root@sdr:/usr/src/SoapyFCDPP/build# SoapySDRUtil --info
######################################################
######################################################

Lib Version: v0.8.0-g351896d3
API Version: v0.8.0
ABI Version: v0.8
Install root: /usr/local
Search path:  /usr/local/lib/SoapySDR/modules0.8
Module found: /usr/local/lib/SoapySDR/modules0.8/libremoteSupport.so  (0.6.0-c09b2f1)
Module found: /usr/local/lib/SoapySDR/modules0.8/libsdrPlaySupport.so (0.3.0-208f95d)
Available factories... remote, sdrplay
Available converters...
 -  CF32 -> [CF32, CS16, CS8, CU16, CU8]
 -  CS16 -> [CF32, CS16, CS8, CU16, CU8]
 -  CS32 -> [CS32]
 -   CS8 -> [CF32, CS16, CS8, CU16, CU8]
 -  CU16 -> [CF32, CS16, CS8]
 -   CU8 -> [CF32, CS16, CS8]
 -   F32 -> [F32, S16, S8, U16, U8]
 -   S16 -> [F32, S16, S8, U16, U8]
 -   S32 -> [S32]
 -    S8 -> [F32, S16, S8, U16, U8]
 -   U16 -> [F32, S16, S8]
 -    U8 -> [F32, S16, S8]

In a Raspberry PI 4 running Raspbian 10.7. Can help me about this error ?

**Comment by guruofquality** [comment]
There was a bad ifdef, can you pull and try again?

**Comment by ea3grn** [comment]
Solved. Thank you very much. You can close this.
