### ISSUE TITLE
SoapyFCDPP under CubicSDR and SDR++

### ISSUE THREAD

**Issue by ghost** [pothosware/SoapyFCDPP#17]
Hello,
I am trying to get my FunCube Dongle Pro+ working under SDR++ using your driver.  I can get it working my FCD working under CubicSDR perfectly with your driver, however, when I first tried it the audio was "choppy" exactly the same way it is under SDR++.  Again, using your driver.  When check the driver settings under CubicSDR there is an additional "Run-time Setting".  I don't know what this is for because there is no label but the lower the number the better.  When I enter 192 into this field (the lowest I can enter, BTW) the audio comes out perfectly.

I am trying to find out where to enter in such a run-time parameter using SDR++.  I have tried asking the author of SDR++ this question and you can see his response here:
https://github.com/AlexandreRouma/SDRPlusPlus/issues/508

![screenshot](https://user-images.githubusercontent.com/87737752/202590773-40b33186-7970-47c4-b690-2cedeb8a2099.png)

Is there another way to enter this parameter to get SDR++ working properly?

Thank you for your time...

**Comment by ghost** [comment]
Oh, yeah.  I'm using Linux Mint, BTW.

**Comment by phlash** [comment]
Hi @vasagle-gleblu, I'm not sure why the name of the run-time setting isn't showing up in Cubic SDR, it should be named `period`.

This setting adjusts the number of samples requested by the SoapyFCDPP driver on each read of the Linux audio system. Smaller values mean smaller blocks of samples, delivered more often - which can help SDR applications to run more smoothly, as you have noticed.

The default value if not specifically set is `sample_rate/4`, which means the SDR gets samples delivered 4 times a second, leading to 'choppy' audio - I will look at changing this default I think..

SDR++ should also be able to adjust the `period` setting but I am not familiar with the UI so cannot tell you where and how to find this - sorry.

**Comment by ghost** [comment]
It points me in the right direction!

Thank you.

**Comment by ghost** [comment]
Any chance you could point me where to make this change to the default value so that I could compile it myself?

**Comment by phlash** [comment]
Sure, it's here: https://github.com/pothosware/SoapyFCDPP/blob/45fb07cf7167849e7e1864559487b15fe338744d/SoapyFCDPP/SoapyFCDPP.cpp#L28
If you know the display frame rate of your SDR, you can pop that in as the divisor.. for example, I use Gqrx at 10hz frame rate, so would set `d_sample_rate/10` as a default. Good luck, have fun :grin:

**Comment by ghost** [comment]
FYI, I changed the divisor to 100.
Worked like a charm.

Thank you.

**Comment by ghost** [comment]
1000 gave better performance. 
:P
