### ISSUE TITLE
License file for SoapyFCDPP project

### ISSUE THREAD

**Issue by guruofquality** [pothosware/SoapyFCDPP#3]
@ast Whats the license for SoapyFCDPP? Can you check in some kind of license file for it. Any standard open source license is probably fine. I need it so I can upload/package this in the PPA, probably needed for debian and others too. Thx

**Comment by ast** [comment]
Which license do you prefer? I don't really care, preferably the one you use on your other modules?

**Comment by guruofquality** [comment]
SoapySDR itself is under a permissive license so people are free to license things as they please. I put everything under the boost software license which is basically like MIT (if you are familiar): 

* https://github.com/pothosware/SoapySDR/blob/master/LICENSE_1_0.txt
* https://web.archive.org/web/20150106221458/http://ideas.opensource.org/ticket/45

Specifically I was really looking for a permissive license that was familiar for gnuradio people (they like to use boost c++ development libs). But I guess thats not too important.

For various hardware modules, I generally take the license that matches the driver. For drivers that are GPL'd, this is basically a requirement (like SoapyUHD). But SoapyBladerf is (LGPL) even though it could probably be anything because libbladerf is lgpl.

But in general, I wanted people to be able to use the Soapy*support module without having to consider that there were any difference license ramifications than the provider of the hardware driver already implied.

Modules that are community provided (ones where didnt write them), thats generally up to the author. Although most of these have often been permissive.

Anyway, so my suggestion is

1) check in a license file (BSL1.0 if you dont care otherwise)
2) and reference it in some way in the sources (example https://github.com/pothosware/SoapySDR/blob/master/lib/DeviceC.cpp)

SPDX came up with a nice way of standardizing referencing licenses without copying the entire LICENSE.TXT into the source every time. Thats what I have been using: https://spdx.org/licenses/

Right now there is `Copyright © 2017 Albin Stigo. All rights reserved.` Which I don't really care personally, but it doesnt really tell folks what the can do with the software, you really want a standard open source license. Plus I think a lot of the linux packagers look at this and would reject it. I think anyway... Did I mention that I'm am not a lawyer :-)

**Comment by ast** [comment]
Boost license sounds good. I will do that... Sorry about that copyright notice. It's just an xcode default header.

**Comment by ast** [comment]
Ok I fixed the license and added some other improvements in the process. Wasn't planning on working much on this as I'm working on another SDR, but I was suddenly inspired.
