### ISSUE TITLE
ppm not working

### ISSUE THREAD

**Issue by loewal** [pothosware/SoapyFCDPP#7]
Hi,
Managed to get the Funcube Pro+ working under OpenwebRX. Thanks for that!
But....the ppm-value has no effect whatsoever.
 "Funcube": {
     "name": "Funcube Pro+",
     "type": "fcdpp",
     "ppm": 8,
     "rf_gain": 0,
     "samp_rate": 192000,
     "profiles": {
This is a universal parameter, so....
Who can help?

**Comment by guruofquality** [comment]
Should be possible with setFrequencyCorrection(). There was just a merge for this that was previously forgotten about: https://github.com/pothosware/SoapyFCDPP/blob/master/SoapyFCDPP/SoapyFCDPP.cpp#L423
