### ISSUE TITLE
Which modules of ALSA are mandatory ?

### ISSUE THREAD

**Issue by J-Luc16** [pothosware/SoapyFCDPP#8]
Hi,

Is alsa-base enough ?

Thanks a lot.
J-Luc F1JEK

**Comment by phlash** [comment]
If you are asking about kernel (kconfig) configuration, then USB_AUDIO (and supporting alsa bits), are required, along with USB_HID.
If you are asking about userspace packages, then `alsa-base` is now quite outdated (https://packages.debian.org/search?keywords=Alsa-base), you should get all the rights bits by installing `libasound2-dev`

Hope this helps :)
